Fix "Fatal error: util.isDate is not a function"
This was doc-only deprecated since Node.js 4,
with runtime warning since Node.js 22,
and finally removed in Node.js 23.

https://nodejs.org/docs/latest/api/deprecations.html#DEP0047

Fix `util.isArray()` while at it, which also has a runtime warning
as of Node.js 22, although still exists as of writing, in Node.js 23.6.

https://nodejs.org/docs/latest/api/deprecations.html#DEP0044